development:
  adapter: postgresql
  encoding: unicode
  database: beta_list_development
  username: postgres
  password: postgres
  pool: 5
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: beta_list_test
  username: postgres
  password: postgres
  pool: 5
  host: localhost

production:
  adapter: postgresql
  encoding: unicode
  database: beta_list_production
  username: postgres
  password: postgres
  pool: 5
  host: localhost
